# Generated by Django 3.2.9 on 2022-05-21 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('deliver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, verbose_name='采购编号')),
                ('purchase_num', models.FloatField(verbose_name='采购数量')),
                ('purchase_time', models.DateField(verbose_name='采购时间')),
                ('purchase_price', models.FloatField(max_length=8, verbose_name='采购的价格')),
                ('deliver_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_of_this_deliver', to='deliver.deliver')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.CharField(blank=True, max_length=8, primary_key=True, serialize=False, verbose_name='供应商编号')),
                ('supplier_add', models.TextField(verbose_name='供应商地址')),
                ('supplier_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='供应商名字')),
                ('supplier_charge_phone', models.PositiveBigIntegerField(verbose_name='供应商负责人电话')),
                ('supplier_charge_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='供应商负责人名字')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='supplier_of_this_product', to='product.product')),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_of_this_supplier', to='purchase.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_root', models.TextField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchase_of_this_product', to='product.product')),
                ('purchase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.purchase')),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchase_of_this_supplier', to='purchase.supplier')),
            ],
        ),
    ]
