# Generated by Django 4.0.3 on 2022-05-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_id',
            field=models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, verbose_name='采购编号'),
        ),
    ]
