# Generated by Django 3.2.9 on 2022-05-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='ucre',
            field=models.IntegerField(default=0, verbose_name='用户积分'),
        ),
    ]
