# Generated by Django 3.2.9 on 2022-05-25 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('pwd', models.CharField(max_length=20, verbose_name='密码')),
                ('mail', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('tel', models.PositiveBigIntegerField(verbose_name='电话号码')),
                ('identity', models.PositiveIntegerField(choices=[(0, '客户'), (1, '采购部'), (2, '物流部'), (3, '仓库部'), (4, '销售部'), (5, '售后部')], default=0, verbose_name='部门')),
                ('staff_id', models.CharField(default=0, max_length=20, verbose_name='员工编号')),
            ],
        ),
    ]
