# Generated by Django 4.0.4 on 2022-05-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='identity',
            field=models.PositiveIntegerField(choices=[(0, '客户'), (1, '采购部'), (2, '物流部'), (3, '仓库部'), (4, '销售部'), (5, '售后部')], default=0, verbose_name='状态'),
        ),
    ]
