# Generated by Django 4.0.3 on 2022-05-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='tel_num',
            field=models.PositiveBigIntegerField(verbose_name='电话号码'),
        ),
    ]
