# Generated by Django 4.0.4 on 2022-05-05 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_userinfo_tel_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='tel_num',
            new_name='tel',
        ),
    ]
