<<<<<<< HEAD
# Generated by Django 3.2.9 on 2022-05-19 20:36
=======
# Generated by Django 4.0.4 on 2022-05-14 19:20
>>>>>>> a42799c1a9e2b422716063a9866b21b2e4fbabd0

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
<<<<<<< HEAD
        ('deliver', '0001_initial'),
        ('warehouse', '0001_initial'),
=======
        ('warehouse', '0001_initial'),
        ('deliver', '0001_initial'),
>>>>>>> a42799c1a9e2b422716063a9866b21b2e4fbabd0
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=8)),
                ('customer_tel', models.CharField(max_length=11)),
                ('customer_cre', models.FloatField(max_length=8)),
                ('customer_add', models.TextField()),
                ('customer_gender', models.BooleanField(verbose_name='性别')),
            ],
        ),
        migrations.CreateModel(
            name='enterprise_flow',
            fields=[
                ('flow_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('num', models.FloatField(max_length=8)),
                ('sender', models.CharField(max_length=20)),
                ('receiver', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('order_price', models.FloatField(max_length=8)),
                ('order_time', models.DateTimeField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.customer')),
                ('deliver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliver.deliver')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('order_detail_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('detail_num', models.FloatField(max_length=8)),
                ('out_time', models.DateTimeField(blank=True, null=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('outward_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.outward')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='AfterSales',
            fields=[
                ('aftersales_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('question_type', models.CharField(max_length=15)),
                ('question_status', models.BooleanField()),
                ('question_discription', models.TextField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
