# Generated by Django 4.0.4 on 2022-05-23 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=8)),
                ('customer_tel', models.CharField(max_length=11)),
                ('customer_cre', models.FloatField(max_length=8)),
                ('customer_add', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='enterprise_flow',
            fields=[
                ('flow_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('num', models.FloatField(max_length=8)),
                ('sender', models.CharField(max_length=20)),
                ('receiver', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('deliver_id', models.CharField(max_length=16)),
                ('order_price', models.FloatField(max_length=8)),
                ('order_time', models.DateTimeField()),
                ('out_time', models.DateTimeField(blank=True, null=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('status_id', models.IntegerField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('order_detail_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('detail_num', models.FloatField(max_length=8)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.orderstatus'),
        ),
        migrations.CreateModel(
            name='AfterSales',
            fields=[
                ('aftersales_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('question_type', models.CharField(max_length=15)),
                ('question_status', models.BooleanField()),
                ('question_discription', models.TextField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
