# Generated by Django 3.2.9 on 2022-05-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliver_id',
            field=models.CharField(max_length=16),
        ),
    ]
