# Generated by Django 3.2.9 on 2022-05-28 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliver', '0002_alter_deliver_deliver_id'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='out_time',
        ),
        migrations.AlterField(
            model_name='order',
            name='deliver_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='deliver.deliver'),
        ),
    ]
