# Generated by Django 3.2.9 on 2022-05-23 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_deliver_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('status_id', models.IntegerField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.orderstatus'),
        ),
    ]
