# Generated by Django 4.0.4 on 2022-05-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20220523_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_gender',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='out_time',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='outward_id',
        ),
        migrations.AddField(
            model_name='order',
            name='out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
