# Generated by Django 3.2.9 on 2022-05-25 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AM',
            fields=[
                ('AM_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=8)),
                ('reason_kind', models.CharField(max_length=8)),
                ('reason_detail', models.CharField(max_length=255)),
                ('AM_status', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='AM_feedback',
            fields=[
                ('order_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='order.order')),
                ('dealingtxt', models.CharField(max_length=255)),
                ('dealing_result', models.CharField(max_length=8)),
            ],
        ),
    ]
