<<<<<<< HEAD
# Generated by Django 3.2.9 on 2022-05-19 20:36
=======
# Generated by Django 4.0.4 on 2022-05-14 19:20
>>>>>>> a42799c1a9e2b422716063a9866b21b2e4fbabd0

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AM',
            fields=[
                ('AM_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=8)),
                ('reason_kind', models.CharField(max_length=8)),
                ('reason_detail', models.CharField(max_length=255)),
                ('AM_status', models.CharField(max_length=8)),
            ],
        ),
    ]
