# Generated by Django 4.0.4 on 2022-05-07 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aftermarket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AM_id', models.CharField(max_length=8)),
                ('order_id', models.CharField(max_length=8)),
                ('reason_text', models.CharField(max_length=50)),
                ('AM_state', models.CharField(max_length=8)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
