# Generated by Django 4.0.4 on 2022-05-23 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_customer_customer_gender_and_more'),
        ('aftermarket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AM_feedback',
            fields=[
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='order.order')),
                ('dealingtxt', models.CharField(max_length=255)),
                ('dealing_result', models.CharField(max_length=8)),
            ],
        ),
    ]
