# Generated by Django 3.2.9 on 2022-05-25 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=55)),
                ('product_type', models.CharField(max_length=55)),
                ('product_price', models.FloatField(default=0.0, max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseDemand',
            fields=[
                ('pdemand_id', models.AutoField(primary_key=True, serialize=False)),
                ('pdemand_num', models.FloatField(max_length=8)),
                ('pdemand_time', models.DateField()),
                ('pdemand_state', models.PositiveIntegerField(choices=[(0, '未完成'), (1, '已完成')], default=0, verbose_name='需求状态')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
