# Generated by Django 4.0.4 on 2022-05-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.FloatField(default=0.0, max_length=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='purchasedemand',
            name='pdemand_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='purchasedemand',
            name='pdemand_state',
            field=models.PositiveIntegerField(choices=[(0, '未完成'), (1, '已完成')], default=0, verbose_name='需求状态'),
        ),
    ]
