# Generated by Django 4.0.3 on 2022-05-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_product_id_alter_product_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedemand',
            name='pdemand_state',
            field=models.PositiveIntegerField(choices=[(0, '未完成'), (1, '已完成')], default=0, verbose_name='需求状态'),
        ),
    ]
