# Generated by Django 4.0.3 on 2022-05-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_purchasedemand_pdemand_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedemand',
            name='pdemand_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
