# Generated by Django 4.0.4 on 2022-05-11 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inward',
            fields=[
                ('purchase_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='purchase.purchase')),
                ('warehouse_flow', models.CharField(default=0, max_length=8, unique=True)),
                ('in_time', models.DateTimeField()),
                ('in_num', models.FloatField(default=0, max_length=8)),
                ('product_name', models.CharField(default='苹果', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WareHouse',
            fields=[
                ('warehouse_flow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='warehouse.inward', to_field='warehouse_flow')),
                ('left_num', models.FloatField(max_length=8)),
                ('warehouse_status', models.CharField(max_length=10)),
            ],
        ),
    ]
