# Generated by Django 4.0.4 on 2022-05-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='left_num',
            field=models.FloatField(default=0, max_length=8),
        ),
    ]
