# Generated by Django 4.0.4 on 2022-05-08 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_alter_inward_purchase_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inward',
            name='warehouse_id',
        ),
        migrations.AddField(
            model_name='inward',
            name='in_num',
            field=models.FloatField(default=0, max_length=8),
        ),
        migrations.AddField(
            model_name='inward',
            name='product_name',
            field=models.CharField(default='苹果', max_length=20),
        ),
        migrations.AddField(
            model_name='inward',
            name='warehouse_flow',
            field=models.CharField(default=0, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='warehouse_flow',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='warehouse.inward', to_field='warehouse_flow'),
        ),
    ]
