# Generated by Django 4.0.4 on 2022-05-08 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_alter_inward_purchase_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inward',
            old_name='warehouse_id',
            new_name='warehouse_flow',
        ),
        migrations.AddField(
            model_name='inward',
            name='in_num',
            field=models.FloatField(default=0, max_length=8),
        ),
        migrations.AddField(
            model_name='inward',
            name='product_name',
            field=models.CharField(default='苹果', max_length=20),
        ),
        migrations.AlterField(
            model_name='inward',
            name='in_time',
            field=models.DateField(),
        ),
    ]
