# Generated by Django 4.0.4 on 2022-05-08 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_rename_warehouse_id_inward_warehouse_flow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inward',
            name='in_time',
            field=models.DateTimeField(),
        ),
    ]
