# Generated by Django 4.0.4 on 2022-05-08 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_remove_inward_warehouse_id_inward_in_num_and_more'),
        ('warehouse', '0005_alter_inward_warehouse_flow_and_more'),
    ]

    operations = [
    ]
