# Generated by Django 4.0.4 on 2022-05-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliver',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, '未分配'), (1, '已分配'), (2, '进行中'), (3, '已完成')], default=0, verbose_name='冷链情况'),
        ),
    ]
