# Generated by Django 4.0.4 on 2022-05-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliver',
            name='deliver_id',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='物流编号'),
        ),
        migrations.AlterField(
            model_name='deliver',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, '未分配'), (1, '已分配'), (2, '进行中'), (3, '已完成')], default=0, verbose_name='订单状态'),
        ),
    ]
