# Generated by Django 3.2.9 on 2022-05-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliver',
            name='deliver_id',
            field=models.CharField(max_length=26, primary_key=True, serialize=False, verbose_name='物流编号'),
        ),
    ]
