# Generated by Django 4.0.4 on 2022-05-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliver', '0002_alter_car_staff_id_alter_carfordeliver_car_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, '空闲中'), (1, '任务中')], default=0, verbose_name='状态'),
        ),
    ]
