# Generated by Django 4.0.4 on 2022-05-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliver', '0003_alter_car_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliver',
            name='departure_time',
            field=models.DateTimeField(null=True, verbose_name='离开时间'),
        ),
    ]
