# Generated by Django 4.0.4 on 2022-05-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliver', '0003_alter_deliverdetail_dd_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverdetail',
            name='dd_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
