# Generated by Django 4.0.4 on 2022-05-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliver', '0004_alter_deliver_departure_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliver',
            name='aim_add',
            field=models.CharField(max_length=30, null=True, verbose_name='目标地点'),
        ),
        migrations.AddField(
            model_name='deliver',
            name='start_add',
            field=models.CharField(max_length=30, null=True, verbose_name='出发地点'),
        ),
    ]
