# Generated by Django 3.2.7 on 2022-06-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='order_detail_status',
            field=models.BooleanField(default=0),
        ),
    ]
