# Generated by Django 4.0.4 on 2022-05-10 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='position',
            field=models.CharField(max_length=10, null=True, verbose_name='职务'),
        ),
    ]
