# Generated by Django 4.0.3 on 2022-05-04 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='department_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_of_this_department', to='personnel.department'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_tel',
            field=models.PositiveBigIntegerField(verbose_name='员工电话'),
        ),
    ]
