# Generated by Django 4.0.3 on 2022-05-04 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_alter_staff_department_id_alter_staff_staff_tel'),
        ('deliver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='personnel.staff', verbose_name='司机的员工ID'),
        ),
        migrations.AlterField(
            model_name='carfordeliver',
            name='car_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='deliver_of_this_car', to='deliver.car', to_field='car_id'),
        ),
        migrations.AlterField(
            model_name='deliverdetail',
            name='deliver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_of_this_deliver', to='deliver.deliver'),
        ),
    ]
