# Generated by Django 4.0.3 on 2022-05-03 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='warehouse_flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse'),
        ),
        migrations.AddField(
            model_name='aftersales',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
        migrations.AlterUniqueTogether(
            name='orderdetail',
            unique_together={('order_id', 'product_id')},
        ),
    ]
